### ISSUE TITLE
how to integrate left planning panel and top filter items as we have in Angular JS Gantt demo 

### ISSUE THREAD

**Issue by akshatgupta02** [danielpalme/NgJsGanttInAngular#8]

**Comment by akshatgupta02** [comment]
![image](https://user-images.githubusercontent.com/32666610/132302292-d0a54b28-e06d-40d1-b4e4-58692df34bff.png)

**Comment by danielpalme** [comment]
Sorry, I don't know. You'll have to investigate yourself.
